GET http://localhost:3000/products HTTP/1.1

###
POST http://localhost:3000/products HTTP/1.1
Content-Type: application/json

{
  "name": "Product 1",
  "description": "Product 1 description",
  "image_url": "https://via.placeholder.com/150",
  "price": 100
}

###
POST http://localhost:3000/auth/login HTTP/1.1
Content-Type: application/json

{
  "username": "chris",
  "password": "chris"
}


###
GET http://localhost:3000/orders HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsInVzZXJuYW1lIjoiY2hyaXMiLCJpYXQiOjE3MDcxNzY3NTUsImV4cCI6MTcwNzE3NjgxNX0.Y4Bmk6ZVuV8fIby9g2_eltTI2aBCuRWdzMXgzJhPXus

###
GET http://localhost:3000/orders/abd0ce93-ff98-4acc-a040-a1500ab4b864 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsInVzZXJuYW1lIjoiY2hyaXMiLCJpYXQiOjE3MDcxNzY3NTUsImV4cCI6MTcwNzE3NjgxNX0.Y4Bmk6ZVuV8fIby9g2_eltTI2aBCuRWdzMXgzJhPXus

###
POST http://localhost:3000/orders HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsInVzZXJuYW1lIjoiY2hyaXMiLCJpYXQiOjE3MDcxNzY3NTUsImV4cCI6MTcwNzE3NjgxNX0.Y4Bmk6ZVuV8fIby9g2_eltTI2aBCuRWdzMXgzJhPXus

{
  "items": [
    {
      "product_id": "04c4353a-3f6d-4272-a8f2-44b82c05ecc0",
      "quantity": 1
    },
    {
      "product_id": "0afa7630-4fc1-4d69-beed-4f8f15becadc",
      "quantity": 1
    }
  ],
  "card_hash": "123"
}